<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Blazorly.Harness.Tools\Blazorly.Harness.Tools.csproj" />
    <ProjectReference Include="..\..\src\Blazorly.Harness.Persistence\Blazorly.Harness.Persistence.csproj" />
    <ProjectReference Include="..\..\src\Blazorly.Harness.Web\Blazorly.Harness.Web.csproj" />
    <ProjectReference Include="..\..\src\Blazorly.Harness.Cli\Blazorly.Harness.Cli.csproj" />
    <ProjectReference Include="..\..\src\Blazorly.Harness.Sdk\Blazorly.Harness.Sdk.csproj" />
  </ItemGroup>

</Project>